spring:
  application:
    name: Aimer-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.aimer.ai: debug